### ISSUE TITLE
Datadog Agent

### ISSUE THREAD

**Issue by myhndl** [polyswarm/arbiter-cuckoo#4]
**Is your feature request related to a problem? Please describe.**
Datadog agent is currently on all engines but Cuckoo. We need to fix this, will help with debugging.

**Describe the solution you'd like**
Hatching to implement, PolySwarm to provide support as necessary.

**Comment by myhndl** [comment]
done

**Comment by jbremer** [comment]
Up and running! Can be closed IMO.
